version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data-agisit:/data/db

  backend:
    image: aaugusto11/server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  webapp:
    image: aaugusto11/web-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data-agisit:
